// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBQVl1Wp_wtKTiKBatOMbQs_KRy3prVWE',
    appId: '1:1046761682065:web:753c6edcd018954035fb30',
    messagingSenderId: '1046761682065',
    projectId: 'momoproxy-44cde',
    authDomain: 'momoproxy-44cde.firebaseapp.com',
    databaseURL: 'https://momoproxy-44cde-default-rtdb.firebaseio.com',
    storageBucket: 'momoproxy-44cde.appspot.com',
    measurementId: 'G-MX6EZX733P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEvJ4csTNJZQHwJtxlgmp_rBtfg5Wk4zw',
    appId: '1:1046761682065:android:cb6ed979553d4ffe35fb30',
    messagingSenderId: '1046761682065',
    projectId: 'momoproxy-44cde',
    databaseURL: 'https://momoproxy-44cde-default-rtdb.firebaseio.com',
    storageBucket: 'momoproxy-44cde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2hjS89ZRXxIyrtnpNo9n0Po_tOLkKzRI',
    appId: '1:1046761682065:ios:a54e4d6190d03d3935fb30',
    messagingSenderId: '1046761682065',
    projectId: 'momoproxy-44cde',
    databaseURL: 'https://momoproxy-44cde-default-rtdb.firebaseio.com',
    storageBucket: 'momoproxy-44cde.appspot.com',
    iosClientId: '1046761682065-prrhsngr2aueur6mdqlide9guirt55p4.apps.googleusercontent.com',
    iosBundleId: 'com.e',
  );
}
